# https://github.com/drduh/config/blob/master/dnscrypt-proxy.toml
# https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml
#dnscrypt_ephemeral_keys = true
#tls_cipher_suite = [52393]  # TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
listen_addresses = ['127.0.0.1:5300']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = false
odoh_servers = false
require_dnssec = false
block_ipv6 = true
block_unqualified = true
block_undelegated = true
reject_ttl = 30
force_tcp = false
timeout = 5000
keepalive = 30
cert_refresh_delay = 240
tls_disable_session_tickets = true
bootstrap_resolvers = ['9.9.9.11:53', '8.8.8.8:53']
ignore_system_dns = false
netprobe_timeout = 60
cache = true
cache_size = 4096
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
forwarding_rules = 'forwarding-rules.txt'
log_level = 2
log_file = 'dnscrypt.log'
log_files_max_size = 10
log_files_max_age = 30
log_files_max_backups = 10
[query_log]
  file = 'query.log'
[nx_log]
  file = 'nx.log'
[blocked_names]
  blocked_names_file = 'blocklist.txt'
  log_file = 'blocked.log'
#[blocked_ips]
#  blocked_ips_file = 'ip-blocklist.txt'
#  log_file = 'ip-blocked.log'
#
#[sources]
#  [sources.public-resolvers]
#    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
#    cache_file = 'public-resolvers.md'
#    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#    refresh_delay = 72
#    prefix = ''
#  [sources.relays]
#    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/relays.md']
#    cache_file = 'relays.md'
#    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#    refresh_delay = 72
#    prefix = ''
#  [sources.quad9-resolvers]
#    urls = ['https://www.quad9.net/quad9-resolvers.md']
#    minisign_key = 'RWQBphd2+f6eiAqBsvDZEBXBGHQBJfeG6G+wJPPKxCZMoEQYpmoysKUN'
#    cache_file = 'quad9-resolvers.md'
#    prefix = 'quad9-'
#
# https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/public-resolvers.md
#[static]
#  [static.quad9-dnscrypt-ip4-filter-ecs-pri-1]
#    stamp = ''sdns://AQMAAAAAAAAADTkuOS45LjExOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA'
#  [static.quad9-dnscrypt-ip4-filter-ecs-pri-2]
#    stamp = 'sdns://AQMAAAAAAAAAEzE0OS4xMTIuMTEyLjExOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA'
#  [static.quad9-dnscrypt-ip4-filter-pri-1]
#    stamp = 'sdns://AQMAAAAAAAAADDkuOS45Ljk6ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0'
#  [static.quad9-dnscrypt-ip4-filter-pri-2]
#    stamp = 'sdns://AQMAAAAAAAAAEjE0OS4xMTIuMTEyLjk6ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0'
#  [static.quad9-dnscrypt-ip4-filter-pri-3]
#    stamp = 'sdns://AQMAAAAAAAAAFDE0OS4xMTIuMTEyLjExMjo4NDQzIGfIR7jIdYzRICRVQ751Z0bfNN8dhMALjEcDaN-CHYY-GTIuZG5zY3J5cHQtY2VydC5xdWFkOS5uZXQ'
#  [static.quad9-dnscrypt-ip4-nofilter-ecs-pri-1]
#    stamp = 'sdns://AQYAAAAAAAAADTkuOS45LjEyOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA'
#  [static.quad9-dnscrypt-ip4-nofilter-ecs-pri-2]
#    stamp = 'sdns://AQYAAAAAAAAAEzE0OS4xMTIuMTEyLjEyOjg0NDMgZ8hHuMh1jNEgJFVDvnVnRt803x2EwAuMRwNo34Idhj4ZMi5kbnNjcnlwdC1jZXJ0LnF1YWQ5Lm5ldA'
